// utils/audioMap.js — AUTO-GENERATED by scripts/generate_audio.js
// Maps narration text -> static .mp3 path in public/assets/audio/

const audioMap = {
  "Sarah sees a sailboat with a triangular sail in Sydney. How does she know how much cloth was used to make that sail? Let us find out what area really means!": "/assets/audio/audio_sarah_sees_a_sailboat_with_a_triangular__0.mp3",
  "John, Mike, Sarah, Priya, Carlos, Yuki, Amara, Elena, Liam, and Mei are Triangle Trekkers — young explorers who measure shapes wherever they travel!": "/assets/audio/audio_john_mike_sarah_priya_carlos_yuki_amara__1.mp3",
  "In Egypt, John looks at a giant pyramid face. \"That's a huge triangle!\" A rectangle appears around it, split right down the middle by a diagonal line.": "/assets/audio/audio_in_egypt_john_looks_at_a_giant_pyramid_f_2.mp3",
  "In Switzerland, Mike sees a triangular flag on a mountain hut. He counts unit squares on a grid — whole squares AND half squares — to find its area.": "/assets/audio/audio_in_switzerland_mike_sees_a_triangular_fl_3.mp3",
  "In Japan, Yuki folds an origami banner. \"Base times height, then split it in half!\" she says. Area = (base × height) ÷ 2. That's the formula!": "/assets/audio/audio_in_japan_yuki_folds_an_origami_banner_ba_4.mp3",
  "Now it's YOUR turn to become a Triangle Trekker! You'll split rectangles, count grid squares, and use the formula to measure triangles all around the world!": "/assets/audio/audio_now_it_s_your_turn_to_become_a_triangle__5.mp3",
  "Drag the line to split the rectangle into two triangles.": "/assets/audio/audio_drag_the_line_to_split_the_rectangle_int_6.mp3",
  "See how one triangle is exactly half the space? That's the secret!": "/assets/audio/audio_see_how_one_triangle_is_exactly_half_the_7.mp3",
  "Count the whole squares and the half squares inside the triangle.": "/assets/audio/audio_count_the_whole_squares_and_the_half_squ_8.mp3",
  "Now fill in the missing number. Six times four, divided by two, equals what?": "/assets/audio/audio_now_fill_in_the_missing_number_six_times_9.mp3",
  "Yes! You measured that triangle perfectly! You're a true Triangle Trekker!": "/assets/audio/audio_yes_you_measured_that_triangle_perfectly_10.mp3",
  "Not quite! Let's look at the shape again.": "/assets/audio/audio_not_quite_let_s_look_at_the_shape_again_11.mp3",
  "What an adventure! Can you tell me one thing you learned about triangles today?": "/assets/audio/audio_what_an_adventure_can_you_tell_me_one_th_12.mp3",
  "Lesson complete! You are an official Triangle Trekker Champion!": "/assets/audio/audio_lesson_complete_you_are_an_official_tria_13.mp3",
  "Badge unlocked! You are a Map Reader!": "/assets/audio/audio_badge_unlocked_you_are_a_map_reader_14.mp3",
  "Badge unlocked! Shape Splitter! You completed all three stations!": "/assets/audio/audio_badge_unlocked_shape_splitter_you_comple_15.mp3",
  "Badge unlocked! Triangle Champion! You scored over eighty percent!": "/assets/audio/audio_badge_unlocked_triangle_champion_you_sco_16.mp3"
};

export default audioMap;
